on:
  push:
    tags:
      - "v*"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: make lint
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: mypy --install-types --non-interactive .
      - run: make type-check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: make test
  build-and-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: make build
      - run: make install
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make integration
        env:
          ATCODER_HELPER_NAME: ${{ secrets.ATCODER_HELPER_NAME }}
          ATCODER_HELPER_PASSWORD: ${{ secrets.ATCODER_HELPER_PASSWORD }}
  release:
    needs: ["lint", "type-check", "test", "build-and-install", "integration"]
    runs-on: ubuntu-latest
    steps:
      - id: get_tag
        run: echo "::set-output name=version::${GITHUB_REF##*/v}"
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-vesrsion: "3.10"
      - run: pip install -r requirements.txt
      - run: sed -i -e 's/__version__ = ".*"/__version__ = "'$VERSION'"/' atcoder_helper/_version.py
        env:
          VERSION: ${{ steps.get_tag.outputs.version}}
      - run: make build
      - run: twine upload dist/*
        env:
          TWINE_USERNAME: ${{secrets.PYPI_USER}}
          TWINE_PASSWORD: ${{secrets.PYPI_PASSWORD}}
